<a href="https://colab.research.google.com/github/Sabari-Raj-Devarajan/EDA/blob/main/25BAI0158_Assessment__2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Merging Employee and Salary Data



###DataFrames for Employees and Salaries

In [ ]:
import pandas as pd

df1_employees = pd.DataFrame({
    'EmployeeID': [1, 3, 5, 7],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Department': ['HR', 'IT', 'Marketing', 'Sales']
})
df2_employees = pd.DataFrame({
    'EmployeeID': [2, 4, 6, 8, 9],
    'Name': ['Kevin', 'Liam', 'Mia', 'Noah', 'Olivia'],
    'Department': ['Sales', 'HR', 'IT', 'Marketing', 'Sales']
})

df1_salaries = pd.DataFrame({
    'EmployeeID': [1, 2, 5, 6, 10, 11],
    'Salary': [60000, 75000, 50000, 80000, 65000, 70000],
    'Bonus': [5000, 7500, 4000, 8000, 6000, 7000]
})
df2_salaries = pd.DataFrame({
    'EmployeeID': [3, 4, 7, 12, 13],
    'Salary': [68000, 82000, 53000, 79000, 67000],
    'Bonus': [6800, 8200, 5300, 7900, 6700]
})

print("Employee Data (df1_employees):\n")
display(df1_employees.head())
print("\nEmployee Data (df2_employees):\n")
display(df2_employees.head())
print("\nSalary Data (df1_salaries):\n")
display(df1_salaries.head())
print("\nSalary Data (df2_salaries):\n")
display(df2_salaries.head())

Employee Data (df1_employees):

   EmployeeID     Name Department
0           1    Alice         HR
1           3      Bob         IT
2           5  Charlie  Marketing
3           7    David      Sales

Employee Data (df2_employees):

   EmployeeID    Name Department
0           2   Kevin      Sales
1           4    Liam         HR
2           6     Mia         IT
3           8    Noah  Marketing
4           9  Olivia      Sales

Salary Data (df1_salaries):

   EmployeeID  Salary  Bonus
0           1   60000   5000
1           2   75000   7500
2           5   50000   4000
3           6   80000   8000
4          10   65000   6000

Salary Data (df2_salaries):

   EmployeeID  Salary  Bonus
0           3   68000   6800
1           4   82000   8200
2           7   53000   5300
3          12   79000   7900
4          13   67000   6700

### Consolidate Employee and Salary DataFrames

In [ ]:
df_employees = pd.concat([df1_employees, df2_employees], ignore_index=True).drop_duplicates(subset=['EmployeeID'])
df_salaries = pd.concat([df1_salaries, df2_salaries], ignore_index=True).drop_duplicates(subset=['EmployeeID'])

print("Combined Employee Data (df_employees):\n")
display(df_employees.head())
print("\nCombined Salary Data (df_salaries):\n")
display(df_salaries.head())

Combined Employee Data (df_employees):

   EmployeeID     Name Department
0           1    Alice         HR
1           3      Bob         IT
2           5  Charlie  Marketing
3           7    David      Sales
4           2    Kevin      Sales

Combined Salary Data (df_salaries):

   EmployeeID  Salary  Bonus
0           1   60000   5000
1           2   75000   7500
2           5   50000   4000
3           6   80000   8000
4          10   65000   6000

### Merging Options for Employee and Salary Data

#### Option 1: Concatenate (axis=1)

In [ ]:
df_employees_indexed = df_employees.reset_index(drop=True)
df_salaries_indexed = df_salaries.reset_index(drop=True)

df_concat_axis1 = pd.concat([df_employees_indexed, df_salaries_indexed], axis=1)
print("Concatenated Data (axis=1):\n")
display(df_concat_axis1.head())

Concatenated Data (axis=1):

   EmployeeID     Name Department  EmployeeID  Salary  Bonus
0         1.0    Alice         HR           1   60000   5000
1         3.0      Bob         IT           2   75000   7500
2         5.0  Charlie  Marketing           5   50000   4000
3         7.0    David      Sales           6   80000   8000
4         2.0    Kevin      Sales          10   65000   6000

#### Option 2: Inner Merge

In [ ]:
df_inner_merge = df_employees.merge(df_salaries, on='EmployeeID', how='inner')
print("Inner Merge (Employees with both info and salary):\n")
display(df_inner_merge.head())
print(f"Number of employees with both records: {len(df_inner_merge)}")

Inner Merge (Employees with both info and salary):

   EmployeeID     Name Department  Salary  Bonus
0           1    Alice         HR   60000   5000
1           3      Bob         IT   68000   6800
2           5  Charlie  Marketing   50000   4000
3           7    David      Sales   53000   5300
4           2    Kevin      Sales   75000   7500

Number of employees with both records: 7

#### Option 3: Left Merge

In [ ]:
df_left_merge = df_employees.merge(df_salaries, on='EmployeeID', how='left')
print("Left Merge (All employees, with salary info if available):\n")
display(df_left_merge.head())
print(f"Total employees in the left merge: {len(df_left_merge)}")

Left Merge (All employees, with salary info if available):

   EmployeeID     Name Department   Salary   Bonus
0           1    Alice         HR  60000.0  5000.0
1           3      Bob         IT  68000.0  6800.0
2           5  Charlie  Marketing  50000.0  4000.0
3           7    David      Sales  53000.0  5300.0
4           2    Kevin      Sales  75000.0  7500.0

Total employees in the left merge: 9

#### Option 4: Right Merge

In [ ]:
df_right_merge = df_employees.merge(df_salaries, on='EmployeeID', how='right')
print("Right Merge (All salary records, with employee info if available):\n")
display(df_right_merge.head())
print(f"Total salary records in the right merge: {len(df_right_merge)}")

missing_employee_info = df_right_merge[df_right_merge['Name'].isnull()]
num_missing_employee_info = len(missing_employee_info)
print(f"\nNumber of salary records with no matching employee info: {num_missing_employee_info}")

if num_missing_employee_info > 0:
    print("Salary records with no matching employee details:\n")
    display(missing_employee_info)

Right Merge (All salary records, with employee info if available):

   EmployeeID     Name Department  Salary  Bonus
0           1    Alice         HR   60000   5000
1           2    Kevin      Sales   75000   7500
2           5  Charlie  Marketing   50000   4000
3           6      Mia         IT   80000   8000
4          10      NaN        NaN   65000   6000

Total salary records in the right merge: 11

Number of salary records with no matching employee info: 4
Salary records with no matching employee details:

    EmployeeID Name Department  Salary  Bonus
4           10  NaN        NaN   65000   6000
5           11  NaN        NaN   70000   7000
9           12  NaN        NaN   79000   7900
10          13  NaN        NaN   67000   6700

## Reshaping with Hierarchical Indexing for Employee Data

In [ ]:
df_hierarchical = df_inner_merge.set_index(['Department', 'Name'])
print("DataFrame with Hierarchical Index:\n")
display(df_hierarchical)

DataFrame with Hierarchical Index:

                    EmployeeID  Salary  Bonus
Department Name
HR         Alice             1   60000   5000
IT         Bob               3   68000   6800
Marketing  Charlie           5   50000   4000
Sales      David             7   53000   5300
           Kevin             2   75000   7500
HR         Liam              4   82000   8200
IT         Mia               6   80000   8000

In [ ]:
stacked_data = df_hierarchical.stack()
print("Stacked Data:\n")
display(stacked_data)

Stacked Data:

Department  Name
HR          Alice    EmployeeID        1
                     Salary        60000
                     Bonus          5000
IT          Bob      EmployeeID        3
                     Salary        68000
                     Bonus          6800
Marketing   Charlie  EmployeeID        5
                     Salary        50000
                     Bonus          4000
Sales       David    EmployeeID        7
                     Salary        53000
                     Bonus          5300
            Kevin    EmployeeID        2
                     Salary        75000
                     Bonus          7500
HR          Liam     EmployeeID        4
                     Salary        82000
                     Bonus          8200
IT          Mia      EmployeeID        6
                     Salary        80000
                     Bonus          8000
dtype: int64

In [ ]:
unstacked_data = stacked_data.unstack()
print("Unstacked Data (default):\n")
display(unstacked_data)

Unstacked Data (default):

                    EmployeeID  Salary  Bonus
Department Name
HR         Alice             1   60000   5000
           Liam              4   82000   8200
IT         Bob               3   68000   6800
           Mia               6   80000   8000
Marketing  Charlie           5   50000   4000
Sales      David             7   53000   5300
           Kevin             2   75000   7500

In [ ]:
unstacked_by_dept = df_hierarchical.unstack(level='Department')
print("Unstacked by Department:\n")
display(unstacked_by_dept)

Unstacked by Department:

           EmployeeID                        Salary                     \
Department         HR   IT Marketing Sales       HR       IT Marketing
Name
Alice             1.0  NaN       NaN   NaN  60000.0      NaN       NaN
Bob               NaN  3.0       NaN   NaN      NaN  68000.0       NaN
Charlie           NaN  NaN       5.0   NaN      NaN      NaN   50000.0
David             NaN  NaN       NaN   7.0      NaN      NaN       NaN
Kevin             NaN  NaN       NaN   2.0      NaN      NaN       NaN
Liam              4.0  NaN       NaN   NaN  82000.0      NaN       NaN
Mia               NaN  6.0       NaN   NaN      NaN  80000.0       NaN

                      Bonus
Department    Sales      HR      IT Marketing   Sales
Name
Alice           NaN  5000.0     NaN       NaN     NaN
Bob             NaN     NaN  6800.0       NaN     NaN
Charlie         NaN     NaN     NaN    4000.0     NaN
David       53000.0     NaN     NaN       NaN  5300.0
Kevin       75000.0     NaN     NaN       NaN  7500.0
Liam            NaN  8200.0     NaN       NaN     NaN
Mia             NaN     NaN  8000.0       NaN     NaN