<a href="https://colab.research.google.com/github/Sabari-Raj-Devarajan/EDA/blob/main/EXP4_28_07_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
#imputation_techniques
import numpy as np
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, SimpleImputer

# Create sample DataFrame with missing values (NaN) for 'Student Performance Data'
df = pd.DataFrame(
    {
        "Student_ID": [1, 2, 3, 4, 5, 6, 7],
        "Exam_Score": [85, np.nan, 72, 90, 68, np.nan, 78],
        "Study_Hours": [5, 3, np.nan, 8, 4, 6, np.nan],
        "Attendance_Percentage": [90, 85, 95, np.nan, 80, 92, 88],
        "Major": ["Math", "Science", "Arts", "Math", np.nan, "Science", "Arts"],
        "Grade": ["A", "B", "C", np.nan, "D", "B", "C"],
    }
)

# 1. Mean Imputation (Numerical - Study_Hours)
mean_imputer = SimpleImputer(strategy="mean")
df["Study_Hours_Mean"] = mean_imputer.fit_transform(df[["Study_Hours"]])

# 2. Median Imputation (Numerical - Exam_Score, robust to outliers)
median_imputer = SimpleImputer(strategy="median")
df["Exam_Score_Median"] = median_imputer.fit_transform(df[["Exam_Score"]])

# 3. Mode Imputation (Categorical - Major and Grade)
mode_imputer_major = SimpleImputer(strategy="most_frequent")
df["Major_Mode"] = mode_imputer_major.fit_transform(df[["Major"]])[:, 0]

mode_imputer_grade = SimpleImputer(strategy="most_frequent")
df["Grade_Mode"] = mode_imputer_grade.fit_transform(df[["Grade"]])[:, 0]

# 4. MICE Imputation (Multivariate Imputation by Chained Equations)
# Select numerical columns for MICE
num_cols_mice = ["Exam_Score", "Study_Hours", "Attendance_Percentage"]
mice_imputer = IterativeImputer(max_iter=10, random_state=42)
df_mice = df[num_cols_mice].copy()
df_mice.iloc[:, :] = mice_imputer.fit_transform(df_mice)
df["Exam_Score_MICE"] = df_mice["Exam_Score"]
df["Study_Hours_MICE"] = df_mice["Study_Hours"]
df["Attendance_Percentage_MICE"] = df_mice["Attendance_Percentage"]

print(df)

   Student_ID  Exam_Score  Study_Hours  Attendance_Percentage    Major Grade  \
0           1        85.0          5.0                   90.0     Math     A
1           2         NaN          3.0                   85.0  Science     B
2           3        72.0          NaN                   95.0     Arts     C
3           4        90.0          8.0                    NaN     Math   NaN
4           5        68.0          4.0                   80.0      NaN     D
5           6         NaN          6.0                   92.0  Science     B
6           7        78.0          NaN                   88.0     Arts     C

   Study_Hours_Mean  Exam_Score_Median Major_Mode Grade_Mode  Exam_Score_MICE  \
0               5.0               85.0       Math          A        85.000000
1               3.0               78.0    Science          B        78.592307
2               5.2               72.0       Arts          C        72.000000
3               8.0               90.0       Math          B        90.000000
4               4.0               68.0       Arts          D        68.000000
5               6.0               78.0    Science          B        78.606220
6               5.2               78.0       Arts          C        78.000000

   Study_Hours_MICE  Attendance_Percentage_MICE
0          5.000000                   90.000000
1          3.000000                   85.000000
2          4.830377                   95.000000
3          8.000000                   88.382692
4          4.000000                   80.000000
5          6.000000                   92.000000
6          5.063917                   88.000000

In [42]:
#Handling missing data
import numpy as np
import pandas as pd

# Handling missing data in a 'Retail Inventory' scenario
# Let's assume we have a dataframe as shown
# This dataframe represents product stock across different warehouses.
data = {
    'Product_ID': ['P001', 'P002', 'P003', 'P004', 'P005'],
    'Warehouse_A_Stock': [100, 150, np.nan, 200, 120],
    'Warehouse_B_Stock': [80, np.nan, 110, 180, np.nan],
    'Warehouse_C_Stock': [np.nan, 130, 90, np.nan, 100]
}
dfx = pd.DataFrame(data)
display(dfx)

# Let's add some more missing values to our dataframe to demonstrate various cases:
dfx['Warehouse_D_Stock'] = np.nan # Entirely NaN column
dfx.loc[5] = ['P006', 70, 90, 80, np.nan] # Add a new product with some stock
dfx.loc[6] = np.nan # Add an entirely NaN row
dfx.loc[6, 'Product_ID'] = 'P007' # Keep Product_ID for the new row
dfx.loc[0, 'Warehouse_A_Stock'] = np.nan # Introduce another specific NaN
dfx.loc[2, 'Warehouse_B_Stock'] = np.nan # Introduce another specific NaN
display(dfx)

# Note the following characteristics of missing values in the preceding dataframe:
# An entire row can contain NaN values.
# An entire column can contain NaN values.
# Some (but not necessarily all) values in both a row and a column can be NaN.

# NaN values in pandas objects
# 1. Check for missing values (boolean mask):
display(dfx.isnull())

# 2. Check for non-missing values (boolean mask):
display(dfx.notnull())

# 3. We can use the sum() method to count the number of NaN values in each column.
display(dfx.isnull().sum())

# 4. We can go one level deeper to find the total number of missing values in the entire DataFrame
display(dfx.isnull().sum().sum())

# 5. So, instead of counting the number of missing values, we can count the number of reported (non-NaN) values per column:
display(dfx.count())

  Product_ID  Warehouse_A_Stock  Warehouse_B_Stock  Warehouse_C_Stock
0       P001              100.0               80.0                NaN
1       P002              150.0                NaN              130.0
2       P003                NaN              110.0               90.0
3       P004              200.0              180.0                NaN
4       P005              120.0                NaN              100.0

,Product_ID,Warehouse_A_Stock,Warehouse_B_Stock,Warehouse_C_Stock,Warehouse_D_Stock
0,P001,NaN,80.0,NaN,NaN
1,P002,150.0,NaN,130.0,NaN
2,P003,NaN,NaN,90.0,NaN
3,P004,200.0,180.0,NaN,NaN
4,P005,120.0,NaN,100.0,NaN
5,P006,70.0,90.0,80.0,NaN
6,P007,NaN,NaN,NaN,NaN

,Product_ID,Warehouse_A_Stock,Warehouse_B_Stock,Warehouse_C_Stock,Warehouse_D_Stock
0,False,True,False,True,True
1,False,False,True,False,True
2,False,True,True,False,True
3,False,False,False,True,True
4,False,False,True,False,True
5,False,False,False,False,True
6,False,True,True,True,True

,Product_ID,Warehouse_A_Stock,Warehouse_B_Stock,Warehouse_C_Stock,Warehouse_D_Stock
0,True,False,True,False,False
1,True,True,False,True,False
2,True,False,False,True,False
3,True,True,True,False,False
4,True,True,False,True,False
5,True,True,True,True,False
6,True,False,False,False,False

Product_ID           0
Warehouse_A_Stock    3
Warehouse_B_Stock    4
Warehouse_C_Stock    3
Warehouse_D_Stock    7
dtype: int64

np.int64(17)

Product_ID           7
Warehouse_A_Stock    4
Warehouse_B_Stock    3
Warehouse_C_Stock    4
Warehouse_D_Stock    0
dtype: int64

In [43]:
# Dropping Missing Values
# One of the ways to handle missing values is to simply remove them from our dataset. We have seen that we can use the `isnull()` and `notnull()` functions from the pandas library to determine null values. Let's see how dropping works on a specific Series (e.g., `Warehouse_A_Stock`) first.

# Let's look at a specific series, e.g., 'Warehouse_A_Stock' with non-null values
display(dfx['Warehouse_A_Stock'][dfx['Warehouse_A_Stock'].notnull()])

# Now, we can use the dropna() method to remove NaN values from this series.
# Note that dropna() returns a copy, it doesn't modify the original Series/DataFrame in-place.
display(dfx['Warehouse_A_Stock'].dropna())

# ### Applying `dropna()` to the entire DataFrame
# If `dropna()` is applied to the entire DataFrame without arguments, it drops any row with at least one NaN value.
display(dfx.dropna())

# ### Dropping by Rows (all NaNs)
# We can drop rows that have ALL NaN values using `how='all'`.
display(dfx.dropna(how='all'))

# ### Dropping by Columns (all NaNs)
# To indicate a check for NaN by columns, we pass `axis=1`.
display(dfx.dropna(how='all', axis=1))

# ### Dropping with a Threshold
# We can also pass another argument, `thresh`, to specify a minimum number of non-NaN values that must exist before the row/column should be kept. For example, to keep columns with at least 4 non-NaN values (excluding 'Product_ID' for this example).
display(dfx.dropna(thresh=4, axis=1))

# 5. Mathematical Operations with NaN
# When performing mathematical operations on Series or DataFrames containing NaN values, pandas (and NumPy) generally propagate the NaNs. This means that if any operand is NaN, the result will also be NaN. However, most aggregation functions have a `skipna` parameter (which defaults to `True`) that allows them to ignore NaN values.

ar1 = np.array([100, 200, np.nan, 300])
ser1 = pd.Series(ar1)

# Mean calculation for numpy array and pandas Series
display(f"Numpy array mean: {ar1.mean()}")
display(f"Pandas Series mean: {ser1.mean()}")

# ### Operations on DataFrame Column (Warehouse_A_Stock)
# Let's compute the sum, average, and cumulative sum for the `Warehouse_A_Stock` column, which contains NaN values.
ser_stock = dfx['Warehouse_A_Stock']

# Total stock (sum)
display(f"Total Warehouse_A_Stock (sum): {ser_stock.sum()}")

# Average stock
display(f"Average Warehouse_A_Stock (mean): {ser_stock.mean()}")

# Cumulative Summing
display(f"Cumulative Sum of Warehouse_A_Stock:\n{ser_stock.cumsum()}")

1    150.0
3    200.0
4    120.0
5     70.0
Name: Warehouse_A_Stock, dtype: float64

1    150.0
3    200.0
4    120.0
5     70.0
Name: Warehouse_A_Stock, dtype: float64

Empty DataFrame
Columns: [Product_ID, Warehouse_A_Stock, Warehouse_B_Stock, Warehouse_C_Stock, Warehouse_D_Stock]
Index: []

,Product_ID,Warehouse_A_Stock,Warehouse_B_Stock,Warehouse_C_Stock,Warehouse_D_Stock
0,P001,NaN,80.0,NaN,NaN
1,P002,150.0,NaN,130.0,NaN
2,P003,NaN,NaN,90.0,NaN
3,P004,200.0,180.0,NaN,NaN
4,P005,120.0,NaN,100.0,NaN
5,P006,70.0,90.0,80.0,NaN
6,P007,NaN,NaN,NaN,NaN

  Product_ID  Warehouse_A_Stock  Warehouse_B_Stock  Warehouse_C_Stock
0       P001                NaN               80.0                NaN
1       P002              150.0                NaN              130.0
2       P003                NaN                NaN               90.0
3       P004              200.0              180.0                NaN
4       P005              120.0                NaN              100.0
5       P006               70.0               90.0               80.0
6       P007                NaN                NaN                NaN

  Product_ID  Warehouse_A_Stock  Warehouse_C_Stock
0       P001                NaN                NaN
1       P002              150.0              130.0
2       P003                NaN               90.0
3       P004              200.0                NaN
4       P005              120.0              100.0
5       P006               70.0               80.0
6       P007                NaN                NaN

'Numpy array mean: nan'

'Pandas Series mean: 200.0'

'Total Warehouse_A_Stock (sum): 540.0'

'Average Warehouse_A_Stock (mean): 135.0'

'Cumulative Sum of Warehouse_A_Stock:\n0      NaN\n1    150.0\n2      NaN\n3    350.0\n4    470.0\n5    540.0\n6      NaN\nName: Warehouse_A_Stock, dtype: float64'

In [44]:
#Filling Missing Values
# We can use the fillna() method to replace NaN values with any particular values.

# Fill all NaN values with 0
filledDf = dfx.fillna(0)
display("DataFrame after filling NaNs with 0:", filledDf)

# Check the difference in means between the original DataFrame (ignoring NaNs) and the one filled with 0
# We use numeric_only=True to ensure only numeric columns are considered for the mean calculation.
display("Mean of original dfx (numeric only):\n", dfx.mean(numeric_only=True))
display("Mean of filledDf (numeric only):\n", filledDf.mean(numeric_only=True))

# Backward and forward filling
# Let's demonstrate ffill and bfill on 'Warehouse_A_Stock' and 'Warehouse_B_Stock'
# Forward-filling (method = 'ffill'): propagates last valid observation forward to next valid observation
display("'Warehouse_A_Stock' with ffill:\n", dfx['Warehouse_A_Stock'].fillna(method='ffill'))
display("'Warehouse_B_Stock' with ffill:\n", dfx['Warehouse_B_Stock'].fillna(method='ffill'))

# Backward-filling (method = 'bfill'): propagates next valid observation backward to next valid observation
display("'Warehouse_A_Stock' with bfill:\n", dfx['Warehouse_A_Stock'].fillna(method='bfill'))
display("'Warehouse_B_Stock' with bfill:\n", dfx['Warehouse_B_Stock'].fillna(method='bfill'))

'DataFrame after filling NaNs with 0:'

,Product_ID,Warehouse_A_Stock,Warehouse_B_Stock,Warehouse_C_Stock,Warehouse_D_Stock
0,P001,0.0,80.0,0.0,0.0
1,P002,150.0,0.0,130.0,0.0
2,P003,0.0,0.0,90.0,0.0
3,P004,200.0,180.0,0.0,0.0
4,P005,120.0,0.0,100.0,0.0
5,P006,70.0,90.0,80.0,0.0
6,P007,0.0,0.0,0.0,0.0

'Mean of original dfx (numeric only):\n'

Warehouse_A_Stock    135.000000
Warehouse_B_Stock    116.666667
Warehouse_C_Stock    100.000000
Warehouse_D_Stock           NaN
dtype: float64

'Mean of filledDf (numeric only):\n'

Warehouse_A_Stock    77.142857
Warehouse_B_Stock    50.000000
Warehouse_C_Stock    57.142857
Warehouse_D_Stock     0.000000
dtype: float64

/tmp/ipykernel_813/3010676486.py:16: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  display("'Warehouse_A_Stock' with ffill:\n", dfx['Warehouse_A_Stock'].fillna(method='ffill'))

"'Warehouse_A_Stock' with ffill:\n"

0      NaN
1    150.0
2    150.0
3    200.0
4    120.0
5     70.0
6     70.0
Name: Warehouse_A_Stock, dtype: float64

/tmp/ipykernel_813/3010676486.py:17: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  display("'Warehouse_B_Stock' with ffill:\n", dfx['Warehouse_B_Stock'].fillna(method='ffill'))

"'Warehouse_B_Stock' with ffill:\n"

0     80.0
1     80.0
2     80.0
3    180.0
4    180.0
5     90.0
6     90.0
Name: Warehouse_B_Stock, dtype: float64

/tmp/ipykernel_813/3010676486.py:20: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  display("'Warehouse_A_Stock' with bfill:\n", dfx['Warehouse_A_Stock'].fillna(method='bfill'))

"'Warehouse_A_Stock' with bfill:\n"

0    150.0
1    150.0
2    200.0
3    200.0
4    120.0
5     70.0
6      NaN
Name: Warehouse_A_Stock, dtype: float64

/tmp/ipykernel_813/3010676486.py:21: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  display("'Warehouse_B_Stock' with bfill:\n", dfx['Warehouse_B_Stock'].fillna(method='bfill'))

"'Warehouse_B_Stock' with bfill:\n"

0     80.0
1    180.0
2    180.0
3    180.0
4     90.0
5     90.0
6      NaN
Name: Warehouse_B_Stock, dtype: float64